-- Baseline reconstruite a partir des gardes de la migration 001 (TEST UNIQUEMENT)
create type secoto_mission_kind as enum ('plateau','convoyage');
create type secoto_frais_type as enum ('essence','peage');
create type secoto_frais_statut as enum ('en_attente','valide','refuse');
create type secoto_doc_type as enum ('devis','bon_de_mission','facture');
create type secoto_doc_statut as enum ('brouillon','envoye','signe','refuse','expire');
create table public.accounts(id uuid primary key, role text not null default 'client', full_name text, company_name text, email text, phone text, city text, status text default 'active', docs_count int default 0, is_verified boolean default false, transporter_type text, client_type text, created_at timestamptz default now());
create table public.mission_requests(id uuid primary key default gen_random_uuid(), public_ref text, status text default 'pending', requester_id uuid, requester_name text, requester_company text, type secoto_mission_kind, from_city text, to_city text, pickup_address text, delivery_address text, mission_date timestamptz, vehicle text, plate text, distance_km numeric, client_name text, client_contact text, client_phone text, price_mode text, proposed_price numeric, notes text, created_by_role text, approved_mission_id uuid, created_at timestamptz default now());
create table public.missions(id uuid primary key default gen_random_uuid(), public_ref text, type text not null default 'convoyage', status text not null default 'published', progress_status text, from_city text, to_city text, pickup_address text, delivery_address text, mission_date timestamptz, vehicle text, plate text, distance_km numeric, carrier_cost numeric, client_price numeric(12,2), carrier_pay numeric(12,2), margin numeric(12,2), client_name text, client_contact text, client_phone text, price_mode text, proposed_price numeric, payment_method text, notes text, created_by_role text, client_account_id uuid references public.accounts(id), assigned_transporter_id uuid references public.accounts(id), assigned_transporter_name text, source_request_id uuid, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.mission_applications(id uuid primary key default gen_random_uuid(), mission_id uuid references public.missions(id), transporter_id uuid, transporter_name text, transporter_company text, transporter_status text, message text, proposed_price numeric, price_note text, status text default 'pending', created_at timestamptz default now());
create table public.documents(id uuid primary key default gen_random_uuid(), mission_id uuid, account_id uuid, recipient_id uuid, type text, file_name text, file_path text, file_url text, status text, doc_type secoto_doc_type, numero text, statut secoto_doc_statut default 'brouillon', needs_signature boolean default false, signed_at timestamptz, emitted_at timestamptz, created_at timestamptz default now(), html_snapshot text);
create table public.mission_tracking_events(id uuid primary key default gen_random_uuid(), mission_id uuid, transporter_id uuid, event_type text, title text, comment text, odometer_km numeric, fuel_level text, issue_type text, issue_severity text, created_at timestamptz default now());
create table public.mission_tracking_photos(id uuid primary key default gen_random_uuid(), tracking_event_id uuid, mission_id uuid, transporter_id uuid, photo_type text, file_name text, file_path text, file_url text, created_at timestamptz default now());
create table public.frais(id uuid primary key default gen_random_uuid(), mission_id uuid, transporter_id uuid, type secoto_frais_type, montant numeric(12,2), justificatif_url text, statut secoto_frais_statut default 'en_attente', motif_refus text, date date, created_at timestamptz default now(), validated_at timestamptz, validated_by uuid);
create table public.notifications(id uuid primary key default gen_random_uuid(), account_id uuid, type text, title text, body text, mission_id uuid, audience text, is_read boolean default false, created_at timestamptz default now());
create table public.app_settings(key text primary key, value jsonb, updated_at timestamptz default now());
create table public.doc_templates(id uuid primary key default gen_random_uuid(), doc_type text, html text);
create or replace function public.secoto_fmt_amount(numeric) returns text language sql immutable as $$ select to_char($1,'FM999G999G990D00') || ' EUR' $$;
create or replace function public.secoto_release_document(uuid) returns void language plpgsql as $$ begin update public.documents set statut='envoye' where id=$1; end $$;
